rsna_zs:
  name: "rsna"
  data_type: "image_classification"
  data_dir: "${base.data_dir}"
  img_dir: "train_images_png"
  data_path: "Mammo-CLIP/src/codebase/data_csv/train_folds_final_1.csv"
  text_max_length: ${base.text_max_length}
  data_frac: 1.0
  label_col: "cancer"